server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
    jmx:
      exposure:
        exclude: "*"
  info:
    build:
      enabled: true
    ssl:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true

spring.security:
  user:
    password: password

encrypt:
  failOnError: false
  key-store:
    location: classpath:keystore.jks
    alias: mytestkey
    password: changeit   # please use environment variables
